AccessModifierIndentation:
  EnforcedStyle: outdent

# "Use alias_method instead of alias"
# We're fine with `alias`.
Alias:
  Enabled: false

AlignParameters:
  EnforcedStyle: with_first_parameter

# Warns when the class is excessively long.
ClassLength:
  Max: 90

# Over time we'd like to get this down, but this is what we're at now.
CyclomaticComplexity:
  Max: 10

# "Avoid the use of the case equality operator ==="
# We prefer using `Class#===` over `Object#is_a?` because `Class#===`
# is less likely to be monkey patched than `is_a?` on a user object.
CaseEquality:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    reduce: 'inject'

# We use YARD to enforce documentation. It works better than rubocop's
# enforcement...rubocop complains about the places we re-open
# `RSpec::Expectations` and `RSpec::Matchers` w/o having doc commments.
Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

# each_with_object is unavailable on 1.8.7 so we have to disable this one.
EachWithObject:
  Enabled: false

Encoding:
  EnforcedStyle: when_needed

FormatString:
  EnforcedStyle: percent

# As long as we support ruby 1.8.7 we have to use hash rockets.
HashSyntax:
  EnforcedStyle: hash_rockets

# We can't use the new lambda syntax, since we still support 1.8.7.
Lambda:
  Enabled: false

# Over time we'd like to get this down, but this is what we're at now.
LineLength:
  Max: 186

# Over time we'd like to get this down, but this is what we're at now.
MethodLength:
  Max: 15

# Who cares what we all the argument for binary operator methods?
OpMethod:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": '[]'

PredicateName:
  NamePrefixBlacklist: ["have_"]

# On 1.8 `proc` is `lambda`, so we use `Proc.new` to ensure we get real procs on all supported versions.
# http://batsov.com/articles/2014/02/04/the-elements-of-style-in-ruby-number-12-proc-vs-proc-dot-new/
Proc:
  Enabled: false

RedundantReturn:
  AllowMultipleReturnValues: true

# We have to rescue Exception in the `raise_error` matcher for it to work properly.
RescueException:
  Enabled: false

# We haven't adopted the `fail` to signal exceptions vs `raise` for re-raises convention.
SignalException:
  Enabled: false

# We've tended to use no space, so it's less of a change to stick with that.
SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# We don't care about single vs double qoutes.
StringLiterals:
  Enabled: false

TrivialAccessors:
  AllowPredicates: true
