source "http://rubygems.org"

gem "rake"
gem "cucumber"
gem "aruba", ">= 0.2.0"
gem "autotest"
gem "diff-lcs"
gem "rspec-expectations", :path => "."
gem "rspec-core", :path => "../rspec-core"
gem "rspec-mocks", :path => "../rspec-mocks"
gem "watchr"
