gem "rake"
gem "jeweler"
gem "cucumber"
gem "aruba"
gem "autotest"
gem "rcov"
gem "mocha"
gem "rr"
gem "flexmock"
gem "rspec-expectations", :path => "../rspec-expectations"
gem "rspec-mocks",        :path => "../rspec-mocks"
