#!/usr/bin/env ruby

require File.expand_path('../../bundle/bundler/setup', __FILE__)
$LOAD_PATH.each do |path|
  next unless path =~ %r|rspec-core/lib$|
  rspec_exe = File.expand_path('../exe/rspec', path)

  if File.exist?(rspec_exe)
    puts rspec_exe
    exit(0)
  end
end

