#!/bin/bash

set -e -x

# Needed by Bundler 1.3: https://github.com/carlhuda/bundler/issues/2382
export RUBYOPT='-rrbconfig'

# idea taken from: http://blog.headius.com/2010/03/jruby-startup-time-tips.html
export JRUBY_OPTS='-X-C' # disable JIT since these processes are so short lived

echo "Bundling Standalone so we can run the specs w/o bundler loaded"

bundle install --standalone --binstubs

echo "Running all..."

bin/rspec spec -b --format progress --profile

echo
echo "--------------------------------------------------------------------"
echo

for file in `find spec -iname '*_spec.rb'`; do
  bin/rspec $file -b --format progress
done

# Prepare RUBYOPT for scenarios that are shelling out to ruby,
# and PATH for those that are using `rspec` or `rake`.
RUBYOPT="-I${PWD}/bundle -rbundler/setup -rrbconfig" \
  PATH="${PWD}/bin:$PATH" \
  bin/cucumber
